### PR TITLE
Add support for Darwin arm64 (M1) build

### PR DESCRIPTION
**Pull request by juusom**
Should fix https://github.com/Shopify/ejson/issues/79 . This seems to work fine on my M1 MacBook.

Edit: I need to get legal approval for the CLA, will try to get it sorted out ASAP.

### CODE REVIEW

**Comment by juusom** [comment]
Does someone need to retrigger the CLA check after signing?

**Comment by bobthebuilderberlin** [comment]
Eagerly waiting for this to be merged...

**Comment by bobthebuilderberlin** [comment]
@burke You seem to be the main contributor. Anything you can do on your side to retrigger the CLA check?

**Comment by burke** [comment]
Sorry for the delay!

**Comment by seanstory** [comment]
> This seems to work fine on my M1 MacBook.

Forgive me if this is obvious, but how can I build this on my M1 MacBook? I'd love to get this back working without needing to wait for a release. Cloning and running `make` is failing with an unhelpful error:
```
$ make
go mod download
go mod tidy
mkdir -p "build/man/man1"
set -euo pipefail ; bundle exec ronn -r --pipe "man/man1/ejson.1.ronn" | gzip > "build/man/man1/ejson.1.gz" || (rm -f "man/man1/ejson.1.ronn" ; false)
make: *** [build/man/man1/ejson.1.gz] Error 1
```

**Comment by juusom** [comment]
I think I had something similar happen but I don't remember what went wrong. Is your git working tree clean? Also, plain `make` also tries to build the debs which is probably not what you want on OS X.  `bundle install` followed by `make setup gem` or `make setup binaries` should do it?

**Comment by escakot** [comment]
Would there be a new version released soon? So it can be installed via bundler?

**Comment by fisherking** [comment]
@burke are you going to bump the new version and publish it to rubygems.org?

**Comment by burke** [comment]
Done, sorry for the delay: https://github.com/Shopify/ejson/releases/tag/v1.3.0

**Pull request merged**
