### PR TITLE
Glide

### PR DESCRIPTION
**Pull request by lxfontes**
This is #30 split up into 2 PRs.

Glide adoption is ramping up, Ex:
https://github.com/kubernetes/kubernetes/pull/24202

r @andremedeiros

### CODE REVIEW

**Comment by andremedeiros** [comment]
This looks good to me. I like how Glide approaches dependency management much like bundler does.

@burke how do you feel?

**Comment by burke** [comment]
ok, as long as it's a trend and not just a preference, :Shipit:

**Comment by burke** [comment]
Oh, we're not vendoring deps though? I'm not totally sure how I feel about that, but I guess if we have the ability to specify by ref it's... okay? I did enjoy the fully-reproducible build idea.

**Comment by lxfontes** [comment]
same feeling here. docs mention it is not necessary (specially if we have rev locks)
https://github.com/Masterminds/glide#q-should-i-check-vendor-into-version-control
I'm fine not having vendor in there (actually like it), but no problem adding it if you guys think it is necessary.

**Pull request merged**
