### PR TITLE
fix compile error problem

### PR DESCRIPTION
**Pull request by funkygao**

### CODE REVIEW

**Comment by burke** [comment]
@andremedeiros @lxfontes this maybe happened when we moved to glide, probably bumped cobra? You guys might have more context.

**Comment by lxfontes** [comment]
they did change the interface, but we are actually locking it properly:
```
import:
- package: github.com/codegangsta/cli
  version: 9908e96513e5a94de37004098a3974a567f18111
```

and that version is still using the old string way
https://github.com/urfave/cli/blob/9908e96513e5a94de37004098a3974a567f18111/help.go#L162

what is going on here:
because we are not checking-in `/vendor`, `go get github.com/shopify/ejson/cmd/ejson` is not using the locked versions :facepalm:

if you download the repo + glide install + go build = it works

vendoring is coming back!

**Comment by lxfontes** [comment]
Fixed via #35 

```
~/c/s/g/shopify ❯❯❯ ls -l $GOPATH/bin/ejson
ls: /Users/lxfontes/code/bin/ejson: No such file or directory
~/c/s/g/shopify ❯❯❯ go get github.com/Shopify/ejson/cmd/ejson                                                                                                                                                                                                                                                               
~/c/s/g/shopify ❯❯❯ echo $?
0
~/c/s/g/shopify ❯❯❯ ls -l $GOPATH/bin/ejson
-rwxr-xr-x  1 lxfontes  staff  4124576  4 Nov 10:08 /Users/lxfontes/code/bin/ejson
```

@funkygao could you please verify?

**Comment by funkygao** [comment]
Yes, it works fine now.
Thanks

**Pull request closed without merging**
