### PR TITLE
Add build for ejson2env and bump to v1.2.0

### PR DESCRIPTION
**Pull request by burke**
cc @Shopify/dev-infra @catherinejones 
Deploying https://github.com/Shopify/ejson/pull/52

### CODE REVIEW

**Comment by lavoiesl** [comment]
```sh
dev up
make
```

```
mkdir -p build/bin/linux-amd64
GOPATH=/Users/seb/src/github.com/Shopify/ejson/Godeps/_workspace:$GOPATH GOOS=linux GOARCH=amd64 go build -o "build/bin/linux-amd64/ejson2env" "github.com/Shopify/ejson/cmd/ejson2env"
cmd/ejson2env/main.go:7:2: cannot find package "github.com/urfave/cli" in any of:
        /Users/seb/src/github.com/Shopify/ejson/vendor/github.com/urfave/cli (vendor tree)
        /Users/seb/.dev/go/1.8.3/src/github.com/urfave/cli (from $GOROOT)
        /Users/seb/src/github.com/Shopify/ejson/Godeps/_workspace/src/github.com/urfave/cli (from $GOPATH)
        /Users/seb/src/github.com/urfave/cli
```

**Comment by burke** [comment]
Try again with that commit ^

**Comment by lavoiesl** [comment]
```
$ dev up
$ make
$ ~/src/github.com/Shopify/ejson/rubygem/bin/ejson2env --version
ejson2env version 1.0.0
$ ~/src/github.com/Shopify/ejson/rubygem/bin/ejson2env secrets.staging.ejson
export ... # works
$ gem install pkg/ejson-1.2.0.gem
$ ejson --version
ejson version 1.2.0
$ ~/src/github.com/Shopify/ejson/rubygem/bin/ejson2env --version
^C/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `require': Interrupt
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1229:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1229:in `<module:Gem>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:116:in `<top (required)>'
        from <internal:gem_prelude>:4:in `require'
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
$ ~/src/github.com/Shopify/ejson/rubygem/bin/ejson2env secrets.staging.ejson
^C/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `require': Interrupt
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1229:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1229:in `<module:Gem>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:116:in `<top (required)>'
        from <internal:gem_prelude>:4:in `require'
        from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

The binary versions work, but the gem version of `ejson2env` hangs (while `ejson` works).

Also, shouldn't `ejson2env`'s version be kept in sync with `ejson`'s?

**Comment by burke** [comment]
Yeah, I'm actually wondering now whether it would be better to make `ejson2env` a completely separate package output.

**Pull request closed without merging**
